baseURL = "https://murph.site/"
languageCode = "zh-cn"
theme = "hyde"
title = "Tomato Punk"
summaryLength = 0
hasCJKLanguage = true

[params]
disqusShortname = "flamingo"
googleAnalytics = "G-9F0K81DG4J"
layoutReverse = false
theme = "hyde"
themeColor = "theme-base-0f"
description = "Hi, 我是Murphy"
[menus]
main = [
    {Name = "Github", URL = "https://github.com/tomatopunk/"},
    {Name = "Mail", URL = "lion.zhang@mail.com"}
]