baseURL = "https://murph.site/"
languageCode = "zh-cn"
theme = "hyde"
title = "Tomato Punk"
summaryLength = 0
hasCJKLanguage = true

[params]
disqusShortname = "flamingo"
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = "theme-base-0c"
description = " "
[menus]
main = [
    {Name = "Github", URL = "https://github.com/tomatopunk/"},
    {Name = "Mail", URL = "lion.zhang@mail.com"}
]