---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*.md"
- type: heading
  label: Documentation
- type: document
  path: README.md
  label: README
  read_only: true
- type: document
  path: FIRSTSTEPS.md
  label: First Steps
  read_only: true
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.55.6'
