name: hexo-deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  deploy:
    type: git
    repo: https://github.com/tomatopunk/tomatopunk.github.io.git
    branch: [gh-pages]
    message: [deploy]